### ISSUE TITLE
make install fatal error

### ISSUE THREAD

**Issue by Lzrnk** [notetau/geany-clang-complete#3]
How to fix this error while make install
g++ -c src/completion.cpp -O2 -fPIC `pkg-config --cflags geany` -std=c++0x -I./geany-complete-core/include -o lib/src/completion.o
src/completion.cpp:32:27: fatal error: clang-c/Index.h: No such file or directory
compilation terminated.
geany-complete-core/Makefile.core:39: recipe for target 'lib/src/completion.o' failed
make: *** [lib/src/completion.o] Error 1

**Comment by notetau** [comment]
You should install the clang development library (such as libclang-dev).

**Comment by b1tfl0w** [comment]
Hello, I fixed in raspbian by adding include and library directories in makefile like this:
`CXXFLAGS += -O2 -I/usr/lib/llvm-3.8/include/`
`LDFLAGS  += -lclang -L/usr/lib/llvm-3.8/lib`
